<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "we_dam2fal"
 *
 * Auto generated by Extension Builder 2013-08-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DAM2FAL',
	'description' => 'This Extension helps you to import your old DAM data into FAL structure.',
	'category' => 'module',
	'author' => 'Daniel Hasse - websedit AG',
	'author_email' => 'extensions@websedit.de',
	'author_company' => 'websedit AG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.6',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0.0-6.1.99',
			'fluid' => '6.0.0-6.1.99',
			'typo3' => '6.0.0-6.1.99',
			'media' => '1.0.0-1.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>